### ISSUE TITLE
Continuous Turn Provider not working Unity 2021.2.1

### ISSUE THREAD

**Issue by MathiasWorm** [Unity-Technologies/XR-Interaction-Toolkit-Examples#114]
Hey all,

it seems like the Continuous Turn Provider is not properly working. When I start my game the "XRI RightHand Locomotion/ Turn" action, which the provider uses by default, not appears in the Input Debugger. The bug causes the provider to not work at all. 

My workaround: Use the "XRI RightHand Locomotion/ Snap Turn"-action in the Continuous Turn Provider. I have also tried to use a custom action ("XRI RightHand Locomotion/ Continuous Turn"), but its still not working. 

Actions:
1.)  New Action Continuous Turn added to XRI RightHand Locomotion action map and tested with the provider (still no changes)
2.)  "Default Continuous Turn.preset"modified accordingly. (Still no changes)
3.)  Use the "XRI RightHand Locomotion/ Snap Turn"-action in Continuous Turn Provider (is works)

**Comment by kevincastejon** [comment]
hi @MathiasWorm , I was struggling the same with the Continous Turn Provider of the "package manager Samples", but I think I eventually figured out it works.
The actions are enabled and disabled by the ControllerInputActionManager that you can find on the hierarchy at "XROriginRig > Camera Offset > LeftController/RightController", here you can setup smooth/snap motion/turn for each left and right controller.
So if you want continous turn on the right hand, just check the **Smooth Turn Enabled** on the right ControllerInputActionManager.
