### ISSUE TITLE
test the functionalities without any accessories, using only the keyboard and mouse

### ISSUE THREAD

**Issue by hernanUOC** [Unity-Technologies/XR-Interaction-Toolkit-Examples#116]
Hello,

We are a group of 30 students utilizing your Unity project on GitHub, the XR Interaction Toolkit Examples - Version 2.3.2, as a learning tool for creating VR games.

Could you please tell us if special VR controllers are required to use your project from Unity's Game View? Or is it possible to test the functionalities without any accessories, using only the keyboard and mouse?

Thank you very much for your assistance.

Best regards,
Hernan

**Comment by mikeNspired** [comment]
In the samples in the package manager you can find XR Device Simulator. I work on VR as my day job and never put on a headset till its almost near delivery time since I can test everything from mouse and keyboard.

**Comment by hernanUOC** [comment]
thank you so much

> In the samples in the package manager you can find XR Device Simulator. I work on VR as my day job and never put on a headset till its almost near delivery time since I can test everything from mouse and keyboard.
