### ISSUE TITLE
[VR] The type or namespace name 'InputHelpers' could not be found

### ISSUE THREAD

**Issue by hash280689** [Unity-Technologies/XR-Interaction-Toolkit-Examples#15]
I have imported everything I need to get the project started but I'm still getting these errors from the "ControllerManager" class. Is there a package I'm missing?

Opened with 2019.3.0f3

**Comment by michaelmarkman** [comment]
Also having this issue, with 2019.30f5

**Comment by IanMcCabe** [comment]
Same here. Seems like it was cause by @StayTalm fix "ControllerManager Fix For Teleport (#13)" yesterday.

**Comment by davidezordan** [comment]
Same here, using 2019.30f5

**Comment by EsimioJ** [comment]
> Same here. Seems like it was a result of @StayTalm's fix "ControllerManager Fix For Teleport (#13)" yesterday. Reverting back to the previous commit "Delete Physics ... " can be used as a temporary fix.

Same here with 2019.3.0f5. 
Can you teach me how to download the previous commit?
thanks!

**Comment by EsimioJ** [comment]
here https://github.com/Unity-Technologies/XR-Interaction-Toolkit-Examples/tree/221a1179d69ed1e6ef781bd44e7b527b6377ebbb
is the workaroud from Ian
works to me

**Comment by mattdatwork** [comment]
Should now be fixed in the 0.9.3 version :)

**Comment by IanMcCabe** [comment]
For clarification. This issue was resolved by updating the Unity Package "XR Interaction Toolkit" to Version 0.9.3 through the Package Manager.

**Comment by StayTalm** [comment]
@IanMcCabe 
You are correct!
This was my slip-up, going forward we will be branching off releases, as right now it's not easy to have 1 private and 1 public repo with interdependencies.  You will still be able to view our PRs for future work on the examples repo, but we will be clearer about which "XR Interaction Toolkit" versions use which versions of the sample.

**Comment by Manick94** [comment]
> here https://github.com/Unity-Technologies/XR-Interaction-Toolkit-Examples/tree/221a1179d69ed1e6ef781bd44e7b527b6377ebbb is the workaroud from Ian works to me

Works like a charm!!!
