### ISSUE TITLE
[AR]Can't move placementInteractable from table to floor

### ISSUE THREAD

**Issue by Goya-** [Unity-Technologies/XR-Interaction-Toolkit-Examples#28]
1. Scan a table and a floor
2. place a cube on table
3. tap to select the cube
4. drag the cube to floor

The cube's positionY is same as table, can't place to the floor plane.
Runnning on iPhone11, build with Unity 2019 3.3f , XR interaction toolkit  is 0.9.3.

**Comment by sivatejachigicherla** [comment]
Please have a look at this 
https://www.youtube.com/watch?v=3IEilGl-mm0

**Comment by andybak** [comment]
@Goya- Could you explain whatever resolved this for you so others can benefit?
