### ISSUE TITLE
Can't get example projects to run as expected

### ISSUE THREAD

**Issue by MarcPilgaard** [Unity-Technologies/XR-Interaction-Toolkit-Examples#31]
I can't seem to get the example projects to run as expected:

WorldInteractionDemo:
- My player levitates 2 meters above the starting area
- I can't teleport to anything. A blue ray, indicate that I should be able to teleport, but nothing happens regardless of what I push on the controllers

I am using an Oculus Rift S. All Oculus drivers are fully updated.
I have tried both Unity 2019.3.0f6 and 2019.3.6f1.
I already run the guardian setup, but that did nothing for the levitate issue.

**Comment by MarcPilgaard** [comment]
Alright, I seem to have solved the issues:
- Regarding levitation I just [changed the Tracking Origin Mode: ](https://github.com/Unity-Technologies/XR-Interaction-Toolkit-Examples/issues/1#issuecomment-604913872)

- In regards to the failing teleport, I just failed to use the right combination of buttons. In order to teleport on Oculus Rift or Oculus Quest you need to:

1. Initiate teleporting by clicking "Y"
2. Use the trigger to execute the teleport

I have not experienced this approach for teleporting before so it came as a suprise that it is a two button action to do.

**Comment by andybak** [comment]
> I have not experienced this approach for teleporting before so it came as a suprise that it is a two button action to do.

That threw me when I tried the scene. I'd argue it's a bug as it's so undiscoverable and unconventional.

@mattdatwork would you be open to changing that? Shall I open a new ticket?
