### ISSUE TITLE
[Bug][XRI 1.0.0-pre.6] XR Controllers stop working after dismissing the Oculus System Keyboard

### ISSUE THREAD

**Issue by maskedmouse** [Unity-Technologies/XR-Interaction-Toolkit-Examples#78]
When you use the Oculus system keyboard there is a button to dismiss the keyboard.
However, after pressing that button, the XR controllers in Unity freeze or are not re-activated.

Unity 2021.1.23f1
Oculus XR Plugin 1.10.1-preview.3
XR Plugin Management 4.1.0

Steps to reproduce:
- Set UI Interaction scene in the build settings as first scene
- Build for Android Oculus (Oculus Quest 1)
- Open the system keyboard by clicking on the Input Field
- Dismiss the keyboard by using the button at the right bottom of the keyboard (it's a keyboard icon with an arrow downwards)
- Observe the XR controllers not responding

**Comment by FaiyazMdAbdul** [comment]
* bump *

**Comment by ROBYER1** [comment]
How did you get the system keyboard to appear?

**Comment by maskedmouse** [comment]
> How did you get the system keyboard to appear?

Use the latest LTS and TMPro package. 
Make sure you have a custom main manifest which specifies to use the oculus system keyboard.
So add `<uses-feature android:name="oculus.software.overlay_keyboard" android:required="false"/>`
I placed it above the `<application>`

The original bug that was posted here has been fixed a long time ago.

**Comment by ROBYER1** [comment]
> > How did you get the system keyboard to appear?
> 
> Use the latest LTS and TMPro package. Make sure you have a custom main manifest which specifies to use the oculus system keyboard. So add `<uses-feature android:name="oculus.software.overlay_keyboard" android:required="false"/>` I placed it above the `<application>`
> 
> The original bug that was posted here has been fixed a long time ago.

Can you share your manifest please? I got it to flash the keyboard once when clicking an input field but otherwise it never shows and I even tried rebuilding with the same issue the keyboard would never show, using Oculus plugin, all packages updated in Unity 2020.3.46f1

**Comment by maskedmouse** [comment]
> Can you share your manifest please?
It is the standard Unity generated manifest with only the uses-feature added. There's nothing else added to it.

Since you're using 2020.3, I suggest updating to 2021.3 or 2022.3. (Rather 2022.3 than 2021.3)
There have been so many fixes over the years that may not always be included in older versions. 2020.3 LTS is already out of support if I'm not mistaken.

If you need further help then this is not the place.
Feel free to create a forum post on the Unity forum (VR section).
